name: PHP CI

on:
  push:
    branches:
      - main
      - JuRo
      - TiNa

  pull_request:
    branches:
      - main
      - JuRo
      - TiNa

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Install dependencies
        run: docker compose exec php composer install

      - name: Run PHPStan
        run: docker compose exec php vendor/bin/phpstan analyze

      - name: Run PHPCS
        run: docker compose exec php vendor/bin/phpcs

      - name: Run PHPUnit
        run: docker compose exec php bin/phpunit
